version: '3'
services: 
  ubuntu:
    image: ubuntu:14.10
    restart: always
  reverseproxy:
    image: reverseproxy
    ports:
      - 8080:8080
      - 5000:5000
    restart: always
  nginx:
    depends_on: 
      - reverseproxy
    image: nginx:1.14.0
    restart: always
  python:
    depends_on:
      - nginx
    image: python:3.4.7
    restart: always
    
