version: '3'  
services: 
  ubuntu:
    image: ubuntu:14.10
    restart: always
  nginx:
    image: nginx:1.14.0
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./docker/config/:/etc/nginx/
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py  
    restart: always

