version: '3'
services: 
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
  nginx:
    image: nginx
    restart: always
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    
