version: '3'
services: 
  ubuntu:
     image: ubuntu:14.10
     restart: always
  nginx:
     image: nginx:1.14.0
     restart: always
     ports:
       - "8080:80"
       - "5000:5000"
  web:
     depends_on:
       - nginx
     build: .
     restart: always

