version: '3'
services: 
  nginx:
     image: nginx:1.14.0
     restart: always
     ports:
       - "8080:80"
  web:
     depends_on:
       - nginx
     build: .
     restart: always
     ports:
        - "5000:5000"

