version: '2'
services: 
 nginx:
    image: nginx:1.14.0
    restart: always
    ports:
      - "8080:80"
    volumes: 
      - "./default.conf:/etc/nginx/conf.d/default.conf"
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py  

