version: '3'

services:
    image: nginx:1.14.0
    volumes: 
      - ./docker/config/:/etc/nginx/
     restart: always
     ports:
      - "8080:80"
     environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
     
    python:
      image: python:3.4
      restart: always
    
